#import "../CoreFoundation/Types.h"
#import "Types.h"

CFTypeID CGPathGetTypeID(void);
CFTypeID CGImageGetTypeID(void);
CFTypeID CGColorGetTypeID(void);
CFTypeID CGPatternGetTypeID(void);
CFTypeID CGFontGetTypeID(void);

CFTypeRef CGCFRetain(CFTypeRef cf);
CFTypeRef CGTypeCreateInstance(CFTypeID typeID, CFIndex extraBytes);
CFTypeRef CGCFDictionaryGetValueWithType(CFDictionaryRef theDict, const void* key, CFTypeID typeID);

CFDictionaryRef CGRectCreateDictionaryRepresentation(CGRect rect);
CFDictionaryRef _imp__CGRectCreateDictionaryRepresentation(CGRect rect);
CFDictionaryRef CGSizeCreateDictionaryRepresentation(CGSize size);
CFDictionaryRef _imp__CGSizeCreateDictionaryRepresentation(CGSize size);
CFDictionaryRef CGPointCreateDictionaryRepresentation(CGPoint point);
CFDictionaryRef _imp__CGPointCreateDictionaryRepresentation(CGPoint point);

CFMutableDictionaryRef CGCFDictionaryCreate(void);
CFMutableDictionaryRef _imp__CGCFDictionaryCreate(void);
CFMutableDictionaryRef CGCFDictionaryCreateCopy(CFDictionaryRef theDict);
CFMutableDictionaryRef _imp__CGCFDictionaryCreateCopy(CFDictionaryRef theDict);

CFArrayRef CGCFDictionaryCopyKeys(CFDictionaryRef theDict, const CFArrayCallBacks* callBacks);
CFArrayRef _imp__CGCFDictionaryCopyKeys(CFDictionaryRef theDict, const CFArrayCallBacks* callBacks);
CFArrayRef CGCFDictionaryCopyValues(CFDictionaryRef theDict, const CFArrayCallBacks* callBacks);
CFArrayRef _imp__CGCFDictionaryCopyValues(CFDictionaryRef theDict, const CFArrayCallBacks* callBacks);

CGRect CGRectInset(CGRect rect, CGFloat dx, CGFloat dy);
CGRect _imp__CGRectInset(CGRect rect, CGFloat dx, CGFloat dy);
CGRect CGRectUnion(CGRect rect1, CGRect rect2);
CGRect _imp__CGRectUnion(CGRect rect1, CGRect rect2);
CGRect CGRectApplyAffineTransform(CGRect rect, CGAffineTransform t);
CGRect _imp__CGRectApplyAffineTransform(CGRect rect, CGAffineTransform t);
CGRect CGContextGetPathBoundingBox(CGContextRef context);
CGRect _imp__CGContextGetPathBoundingBox(CGContextRef context);
CGRect CGContextGetClipBoundingBox(CGContextRef c);
CGRect _imp__CGContextGetClipBoundingBox(CGContextRef c);
CGRect CGPathGetBoundingBox(CGPathRef path);
CGRect _imp__CGPathGetBoundingBox(CGPathRef path);
CGRect CGPathGetPathBoundingBox(CGPathRef path);
CGRect _imp__CGPathGetPathBoundingBox(CGPathRef path);
CGRect CGRectStandardize(CGRect rect);
CGRect _imp__CGRectStandardize(CGRect rect);
CGRect CGRectOffset(CGRect rect, CGFloat dx, CGFloat dy);
CGRect _imp__CGRectOffset(CGRect rect, CGFloat dx, CGFloat dy);
CGRect CGRectIntegral(CGRect rect);
CGRect _imp__CGRectIntegral(CGRect rect);
CGRect CGRectIntersection(CGRect r1, CGRect r2);
CGRect _imp__CGRectIntersection(CGRect r1, CGRect r2);

CGPoint CGPointApplyAffineTransform(CGPoint point, CGAffineTransform t);
CGPoint _imp__CGPointApplyAffineTransform(CGPoint point, CGAffineTransform t);
CGPoint CGContextGetPathCurrentPoint(CGContextRef context);
CGPoint _imp__CGContextGetPathCurrentPoint(CGContextRef context);
CGPoint CGPathGetCurrentPoint(CGPathRef path);
CGPoint _imp__CGPathGetCurrentPoint(CGPathRef path);

CGSize CGSizeApplyAffineTransform(CGSize size, CGAffineTransform t);
CGSize _imp__CGSizeApplyAffineTransform(CGSize size, CGAffineTransform t);

CGFloat CGRectGetWidth(CGRect rect);
CGFloat _imp__CGRectGetWidth(CGRect rect);
CGFloat CGRectGetHeight(CGRect rect);
CGFloat _imp__CGRectGetHeight(CGRect rect);
CGFloat CGRectGetMaxX(CGRect rect);
CGFloat _imp__CGRectGetMaxX(CGRect rect);
CGFloat CGRectGetMidX(CGRect rect);
CGFloat _imp__CGRectGetMidX(CGRect rect);
CGFloat CGRectGetMinX(CGRect rect);
CGFloat _imp__CGRectGetMinX(CGRect rect);
CGFloat CGRectGetMaxY(CGRect rect);
CGFloat _imp__CGRectGetMaxY(CGRect rect);
CGFloat CGRectGetMidY(CGRect rect);
CGFloat _imp__CGRectGetMidY(CGRect rect);
CGFloat CGRectGetMinY(CGRect rect);
CGFloat _imp__CGRectGetMinY(CGRect rect);
CGFloat CGColorGetAlpha(CGColorRef color);
CGFloat _imp__CGColorGetAlpha(CGColorRef color);
CGFloat CGContextGetAlpha(CGContextRef c);
CGFloat _imp__CGContextGetAlpha(CGContextRef c);

CGBlendMode CGContextGetBlendMode(CGContextRef c);
CGBlendMode _imp__CGContextGetBlendMode(CGContextRef c);

void CGContextSaveGState(CGContextRef c);
void _imp__CGContextSaveGState(CGContextRef c);
void CGContextRestoreGState(CGContextRef c);
void _imp__CGContextRestoreGState(CGContextRef c);
void CGContextScaleCTM(CGContextRef c, CGFloat sx, CGFloat sy);
void _imp__CGContextScaleCTM(CGContextRef c, CGFloat sx, CGFloat sy);
void CGContextTranslateCTM(CGContextRef c, CGFloat tx, CGFloat ty);
void _imp__CGContextTranslateCTM(CGContextRef c, CGFloat tx, CGFloat ty);
void CGContextRotateCTM(CGContextRef c, CGFloat angle);
void _imp__CGContextRotateCTM(CGContextRef c, CGFloat angle);
void CGContextConcatCTM(CGContextRef c, CGAffineTransform transform);
void _imp__CGContextConcatCTM(CGContextRef c, CGAffineTransform transform);
void CGContextSetBlendMode(CGContextRef c, CGBlendMode mode);
void _imp__CGContextSetBlendMode(CGContextRef c, CGBlendMode mode);
void CGContextSetLineWidth(CGContextRef c, CGFloat width);
void _imp__CGContextSetLineWidth(CGContextRef c, CGFloat width);
void CGContextBeginPath(CGContextRef c);
void _imp__CGContextBeginPath(CGContextRef c);
void CGContextMoveToPoint(CGContextRef c, CGFloat x, CGFloat y);
void _imp__CGContextMoveToPoint(CGContextRef c, CGFloat x, CGFloat y);
void CGContextAddLineToPoint(CGContextRef c, CGFloat x, CGFloat y);
void _imp__CGContextAddLineToPoint(CGContextRef c, CGFloat x, CGFloat y);
void CGContextAddCurveToPoint(CGContextRef c, CGFloat cp1x, CGFloat cp1y, CGFloat cp2x, CGFloat cp2y, CGFloat x, CGFloat y);
void _imp__CGContextAddCurveToPoint(CGContextRef c, CGFloat cp1x, CGFloat cp1y, CGFloat cp2x, CGFloat cp2y, CGFloat x, CGFloat y);
void CGContextAddQuadCurveToPoint(CGContextRef c, CGFloat cpx, CGFloat cpy, CGFloat x, CGFloat y);
void _imp__CGContextAddQuadCurveToPoint(CGContextRef c, CGFloat cpx, CGFloat cpy, CGFloat x, CGFloat y);
void CGContextClosePath(CGContextRef c);
void _imp__CGContextClosePath(CGContextRef c);
void CGContextAddRect(CGContextRef c, CGRect rect);
void _imp__CGContextAddRect(CGContextRef c, CGRect rect);
void CGContextAddRects(CGContextRef c, const CGRect rects[], size_t count);
void _imp__CGContextAddRects(CGContextRef c, const CGRect rects[], size_t count);
void CGContextAddLines(CGContextRef c, const CGPoint points[], size_t count);
void _imp__CGContextAddLines(CGContextRef c, const CGPoint points[], size_t count);
void CGContextAddEllipseInRect(CGContextRef context, CGRect rect);
void _imp__CGContextAddEllipseInRect(CGContextRef context, CGRect rect);
void CGContextAddArc(CGContextRef c, CGFloat x, CGFloat y, CGFloat radius, CGFloat startAngle, CGFloat endAngle, int clockwise);
void _imp__CGContextAddArc(CGContextRef c, CGFloat x, CGFloat y, CGFloat radius, CGFloat startAngle, CGFloat endAngle, int clockwise);
void CGContextAddArcToPoint(CGContextRef c, CGFloat x1, CGFloat y1, CGFloat x2, CGFloat y2, CGFloat radius);
void _imp__CGContextAddArcToPoint(CGContextRef c, CGFloat x1, CGFloat y1, CGFloat x2, CGFloat y2, CGFloat radius);
void CGContextReplacePathWithStrokedPath(CGContextRef c);
void _imp__CGContextReplacePathWithStrokedPath(CGContextRef c);
void CGContextAddPath(CGContextRef c, CGPathRef path);
void _imp__CGContextAddPath(CGContextRef c, CGPathRef path);
void CGContextFillPath(CGContextRef c);
void _imp__CGContextFillPath(CGContextRef c);
void CGContextEOFillPath(CGContextRef c);
void _imp__CGContextEOFillPath(CGContextRef c);
void CGContextStrokePath(CGContextRef c);
void _imp__CGContextStrokePath(CGContextRef c);
void CGContextDrawImage(CGContextRef c, CGRect rect, CGImageRef image);
void _imp__CGContextDrawImage(CGContextRef c, CGRect rect, CGImageRef image);
void CGContextFillRect(CGContextRef c, CGRect rect);
void _imp__CGContextFillRect(CGContextRef c, CGRect rect);
void CGContextFillRects(CGContextRef c, const CGRect rects[], size_t count);
void _imp__CGContextFillRects(CGContextRef c, const CGRect rects[], size_t count);
void CGContextStrokeRect(CGContextRef c, CGRect rect);
void _imp__CGContextStrokeRect(CGContextRef c, CGRect rect);
void CGContextStrokeRectWithWidth(CGContextRef c, CGRect rect, CGFloat width);
void _imp__CGContextStrokeRectWithWidth(CGContextRef c, CGRect rect, CGFloat width);
void CGContextClearRect(CGContextRef c, CGRect rect);
void _imp__CGContextClearRect(CGContextRef c, CGRect rect);
void CGContextFillEllipseInRect(CGContextRef context, CGRect rect);
void _imp__CGContextFillEllipseInRect(CGContextRef context, CGRect rect);
void CGContextStrokeEllipseInRect(CGContextRef context, CGRect rect);
void _imp__CGContextStrokeEllipseInRect(CGContextRef context, CGRect rect);
void CGContextStrokeLineSegments(CGContextRef c, const CGPoint points[], size_t count);
void _imp__CGContextStrokeLineSegments(CGContextRef c, const CGPoint points[], size_t count);
void CGContextClip(CGContextRef c);
void _imp__CGContextClip(CGContextRef c);
void CGContextEOClip(CGContextRef c);
void _imp__CGContextEOClip(CGContextRef c);
void CGContextClipToMask(CGContextRef c, CGRect rect, CGImageRef mask);
void _imp__CGContextClipToMask(CGContextRef c, CGRect rect, CGImageRef mask);
void CGContextClipToRect(CGContextRef c, CGRect rect);
void _imp__CGContextClipToRect(CGContextRef c, CGRect rect);
void CGContextClipToRects(CGContextRef c, const CGRect rects[], size_t count);
void _imp__CGContextClipToRects(CGContextRef c, const CGRect rects[], size_t count);
void CGContextSetFillColor(CGContextRef context, const CGFloat components[]);
void _imp__CGContextSetFillColor(CGContextRef context, const CGFloat components[]);
void CGContextSetFillColorWithColor(CGContextRef c, CGColorRef color);
void _imp__CGContextSetFillColorWithColor(CGContextRef c, CGColorRef color);
void CGContextSetStrokeColor(CGContextRef context, const CGFloat components[]);
void _imp__CGContextSetStrokeColor(CGContextRef context, const CGFloat components[]);
void CGContextSetStrokeColorWithColor(CGContextRef c, CGColorRef color);
void _imp__CGContextSetStrokeColorWithColor(CGContextRef c, CGColorRef color);
void CGContextSetInterpolationQuality(CGContextRef c, CGInterpolationQuality quality);
void _imp__CGContextSetInterpolationQuality(CGContextRef c, CGInterpolationQuality quality);
void CGContextSetShadowWithColor(CGContextRef c, CGSize offset, CGFloat blur, CGColorRef color);
void _imp__CGContextSetShadowWithColor(CGContextRef c, CGSize offset, CGFloat blur, CGColorRef color);
void CGContextRelease(CGContextRef c);
void _imp__CGContextRelease(CGContextRef c);
void CGContextFlush(CGContextRef c);
void _imp__CGContextFlush(CGContextRef c);
void CGContextSynchronize(CGContextRef c);
void _imp__CGContextSynchronize(CGContextRef c);
void CGContextEndPage(CGContextRef c);
void _imp__CGContextEndPage(CGContextRef c);
void CGContextBeginPage(CGContextRef c, const CGRect* mediaBox);
void _imp__CGContextBeginPage(CGContextRef c, const CGRect* mediaBox);
void CGContextDrawPath(CGContextRef c, CGPathDrawingMode mode);
void _imp__CGContextDrawPath(CGContextRef c, CGPathDrawingMode mode);
void CGContextResetClip(CGContextRef c);
void _imp__CGContextResetClip(CGContextRef c);
void CGContextClear(CGContextRef c);
void _imp__CGContextClear(CGContextRef c);
void CGGradientRelease(CGGradientRef gradient);
void _imp__CGGradientRelease(CGGradientRef gradient);
void CGImageRelease(CGImageRef image);
void _imp__CGImageRelease(CGImageRef image);
void CGPathAddPath(CGMutablePathRef path1, const CGAffineTransform* m, CGPathRef path2);
void _imp__CGPathAddPath(CGMutablePathRef path1, const CGAffineTransform* m, CGPathRef path2);
void CGPathAddArc(CGMutablePathRef path, const CGAffineTransform* m, CGFloat x, CGFloat y, CGFloat radius, CGFloat startAngle, CGFloat endAngle, bool clockwise);
void _imp__CGPathAddArc(CGMutablePathRef path, const CGAffineTransform* m, CGFloat x, CGFloat y, CGFloat radius, CGFloat startAngle, CGFloat endAngle, bool clockwise);
void CGPathAddRelativeArc(CGMutablePathRef path, const CGAffineTransform* matrix, CGFloat x, CGFloat y, CGFloat radius, CGFloat startAngle, CGFloat delta);
void _imp__CGPathAddRelativeArc(CGMutablePathRef path, const CGAffineTransform* matrix, CGFloat x, CGFloat y, CGFloat radius, CGFloat startAngle, CGFloat delta);
void CGPathAddArcToPoint(CGMutablePathRef path, const CGAffineTransform* m, CGFloat x1, CGFloat y1, CGFloat x2, CGFloat y2, CGFloat radius);
void _imp__CGPathAddArcToPoint(CGMutablePathRef path, const CGAffineTransform* m, CGFloat x1, CGFloat y1, CGFloat x2, CGFloat y2, CGFloat radius);
void CGPathAddCurveToPoint(CGMutablePathRef path, const CGAffineTransform* m, CGFloat cp1x, CGFloat cp1y, CGFloat cp2x, CGFloat cp2y, CGFloat x, CGFloat y);
void _imp__CGPathAddCurveToPoint(CGMutablePathRef path, const CGAffineTransform* m, CGFloat cp1x, CGFloat cp1y, CGFloat cp2x, CGFloat cp2y, CGFloat x, CGFloat y);
void CGPathAddLines(CGMutablePathRef path, const CGAffineTransform* m, const CGPoint* points, size_t count);
void _imp__CGPathAddLines(CGMutablePathRef path, const CGAffineTransform* m, const CGPoint* points, size_t count);
void CGPathAddLineToPoint(CGMutablePathRef path, const CGAffineTransform* m, CGFloat x, CGFloat y);
void _imp__CGPathAddLineToPoint(CGMutablePathRef path, const CGAffineTransform* m, CGFloat x, CGFloat y);
void CGPathAddQuadCurveToPoint(CGMutablePathRef path, const CGAffineTransform* m, CGFloat cpx, CGFloat cpy, CGFloat x, CGFloat y);
void _imp__CGPathAddQuadCurveToPoint(CGMutablePathRef path, const CGAffineTransform* m, CGFloat cpx, CGFloat cpy, CGFloat x, CGFloat y);
void CGPathAddRect(CGMutablePathRef path, const CGAffineTransform* m, CGRect rect);
void _imp__CGPathAddRect(CGMutablePathRef path, const CGAffineTransform* m, CGRect rect);
void CGPathAddRects(CGMutablePathRef path, const CGAffineTransform* m, const CGRect* rects, size_t count);
void _imp__CGPathAddRects(CGMutablePathRef path, const CGAffineTransform* m, const CGRect* rects, size_t count);
void CGPathAddRoundedRect(CGMutablePathRef path, const CGAffineTransform* transform, CGRect rect, CGFloat cornerWidth, CGFloat cornerHeight);
void _imp__CGPathAddRoundedRect(CGMutablePathRef path, const CGAffineTransform* transform, CGRect rect, CGFloat cornerWidth, CGFloat cornerHeight);
void CGPathApply(CGPathRef path, void* info, CGPathApplierFunction function);
void _imp__CGPathApply(CGPathRef path, void* info, CGPathApplierFunction function);
void CGPathMoveToPoint(CGMutablePathRef path, const CGAffineTransform* m, CGFloat x, CGFloat y);
void _imp__CGPathMoveToPoint(CGMutablePathRef path, const CGAffineTransform* m, CGFloat x, CGFloat y);
void CGPathCloseSubpath(CGMutablePathRef path);
void _imp__CGPathCloseSubpath(CGMutablePathRef path);
void CGPathAddEllipseInRect(CGMutablePathRef path, const CGAffineTransform* m, CGRect rect);
void _imp__CGPathAddEllipseInRect(CGMutablePathRef path, const CGAffineTransform* m, CGRect rect);
void CGPathRelease(CGPathRef path);
void _imp__CGPathRelease(CGPathRef path);
void CGContextDrawLinearGradient(CGContextRef c, CGGradientRef gradient, CGPoint startPoint, CGPoint endPoint, CGGradientDrawingOptions options);
void _imp__CGContextDrawLinearGradient(CGContextRef c, CGGradientRef gradient, CGPoint startPoint, CGPoint endPoint, CGGradientDrawingOptions options);
void CGContextBeginTransparencyLayer(CGContextRef c, CFDictionaryRef auxiliaryInfo);
void _imp__CGContextBeginTransparencyLayer(CGContextRef c, CFDictionaryRef auxiliaryInfo);
void CGContextBeginTransparencyLayerWithRect(CGContextRef c, CGRect rect, CFDictionaryRef auxInfo);
void _imp__CGContextBeginTransparencyLayerWithRect(CGContextRef c, CGRect rect, CFDictionaryRef auxInfo);
void CGContextEndTransparencyLayer(CGContextRef c);
void _imp__CGContextEndTransparencyLayer(CGContextRef c);
void CGRectDivide(CGRect rect, CGRect* slice, CGRect* remainder, CGFloat amount, CGRectEdge edge);
void _imp__CGRectDivide(CGRect rect, CGRect* slice, CGRect* remainder, CGFloat amount, CGRectEdge edge);
void CGColorSpaceRelease(CGColorSpaceRef space);
void _imp__CGColorSpaceRelease(CGColorSpaceRef space);
void CGColorRelease(CGColorRef color);
void _imp__CGColorRelease(CGColorRef color);
void CGPatternRelease(CGPatternRef pattern);
void _imp__CGPatternRelease(CGPatternRef pattern);
void CGFontRelease(CGFontRef font);
void _imp__CGFontRelease(CGFontRef font);

void CGPostError(const char* format, ...);
void CGCFRelease(CFTypeRef cf);
void CGCFDictionaryApplyBlock(CFDictionaryRef theDict, void* context);
void CGCFDictionarySetCString(CFMutableDictionaryRef theDict, const char* cStr);
void CGCFDictionarySetBoolean(CFMutableDictionaryRef theDict, const void* key, bool value);
void CGCFDictionarySetFloat(CFMutableDictionaryRef theDict, const void* key, double value);
void CGCFDictionarySetNumber(CFMutableDictionaryRef theDict, const void* key, CFNumberType type, const void* valuePtr);
void CGCFDictionarySetCFTypeRef(CFMutableDictionaryRef theDict, const void* key, const void* value);

CGPathRef CGPathRetain(CGPathRef path);
CGPathRef _imp__CGPathRetain(CGPathRef path);
CGPathRef CGPathCreateWithEllipseInRect(CGRect rect, const CGAffineTransform* transform);
CGPathRef _imp__CGPathCreateWithEllipseInRect(CGRect rect, const CGAffineTransform* transform);
CGPathRef CGPathCreateWithRect(CGRect rect, const CGAffineTransform* transform);
CGPathRef _imp__CGPathCreateWithRect(CGRect rect, const CGAffineTransform* transform);
CGPathRef CGPathCreateWithRoundedRect(CGRect rect, CGFloat cornerWidth, CGFloat cornerHeight, const CGAffineTransform* transform);
CGPathRef _imp__CGPathCreateWithRoundedRect(CGRect rect, CGFloat cornerWidth, CGFloat cornerHeight, const CGAffineTransform* transform);
CGPathRef CGPathCreateCopy(CGPathRef path);
CGPathRef _imp__CGPathCreateCopy(CGPathRef path);
CGPathRef CGPathCreateCopyByTransformingPath(CGPathRef path, const CGAffineTransform* transform);
CGPathRef _imp__CGPathCreateCopyByTransformingPath(CGPathRef path, const CGAffineTransform* transform);
CGPathRef CGPathCreateCopyByDashingPath(CGPathRef path, const CGAffineTransform* transform, CGFloat phase, const CGFloat* lengths, size_t count);
CGPathRef _imp__CGPathCreateCopyByDashingPath(CGPathRef path, const CGAffineTransform* transform, CGFloat phase, const CGFloat* lengths, size_t count);
CGPathRef CGPathCreateCopyByStrokingPath(CGPathRef path, const CGAffineTransform* transform, CGFloat lineWidth, CGLineCap lineCap, CGLineJoin lineJoin, CGFloat miterLimit);
CGPathRef _imp__CGPathCreateCopyByStrokingPath(CGPathRef path, const CGAffineTransform* transform, CGFloat lineWidth, CGLineCap lineCap, CGLineJoin lineJoin, CGFloat miterLimit);

CGMutablePathRef CGPathCreateMutable(void);
CGMutablePathRef _imp__CGPathCreateMutable(void);
CGMutablePathRef CGPathCreateMutableCopy(CGPathRef path);
CGMutablePathRef _imp__CGPathCreateMutableCopy(CGPathRef path);
CGMutablePathRef CGPathCreateMutableCopyByTransformingPath(CGPathRef path, const CGAffineTransform* transform);
CGMutablePathRef _imp__CGPathCreateMutableCopyByTransformingPath(CGPathRef path, const CGAffineTransform* transform);

CGImageRef CGImageCreate(size_t width, size_t height, size_t bitsPerComponent, size_t bitsPerPixel, size_t bytesPerRow, CGColorSpaceRef space, CGBitmapInfo bitmapInfo, CGDataProviderRef provider, const CGFloat* decode, bool shouldInterpolate, CGColorRenderingIntent intent);
CGImageRef _imp__CGImageCreate(size_t width, size_t height, size_t bitsPerComponent, size_t bitsPerPixel, size_t bytesPerRow, CGColorSpaceRef space, CGBitmapInfo bitmapInfo, CGDataProviderRef provider, const CGFloat* decode, bool shouldInterpolate, CGColorRenderingIntent intent);
CGImageRef CGImageCreateWithPNGDataProvider(CGDataProviderRef source, const CGFloat *decode, bool shouldInterpolate, CGColorRenderingIntent intent);
CGImageRef _imp__CGImageCreateWithPNGDataProvider(CGDataProviderRef source, const CGFloat *decode, bool shouldInterpolate, CGColorRenderingIntent intent);
CGImageRef CGImageMaskCreate(size_t width, size_t height, size_t bitsPerComponent, size_t bitsPerPixel, size_t bytesPerRow, CGDataProviderRef provider, const CGFloat* decode, bool shouldInterpolate);
CGImageRef _imp__CGImageMaskCreate(size_t width, size_t height, size_t bitsPerComponent, size_t bitsPerPixel, size_t bytesPerRow, CGDataProviderRef provider, const CGFloat* decode, bool shouldInterpolate);
CGImageRef CGBitmapContextCreateImage(CGContextRef context);
CGImageRef _imp__CGBitmapContextCreateImage(CGContextRef context);
CGImageRef CGImageRetain(CGImageRef image);
CGImageRef _imp__CGImageRetain(CGImageRef image);

CGFontRef CGFontRetain(CGFontRef font);
CGFontRef _imp__CGFontRetain(CGFontRef font);
CGFontRef CGFontCreateWithFontName(CFStringRef name);
CGFontRef _imp__CGFontCreateWithFontName(CFStringRef name);
CGFontRef CGFontCreateWithDataProvider(CGDataProviderRef provider);
CGFontRef _imp__CGFontCreateWithDataProvider(CGDataProviderRef provider);
CGFontRef CGFontCreateCopyWithVariations(CGFontRef font, CFDictionaryRef variations);
CGFontRef _imp__CGFontCreateCopyWithVariations(CGFontRef font, CFDictionaryRef variations);

CGFontRef CGFontCreateWithName(const char* name);
CGFontRef _imp__CGFontCreateWithName(const char* name);
CGFontRef CGFontCreateMatchingFont(const char* , const char* , int, bool, CGFloat);
CGFontRef _imp__CGFontCreateMatchingFont(const char* , const char* , int, bool, CGFloat);

CFMutableArrayRef CGFontCreateFontsWithPath(CFStringRef path);
CFMutableArrayRef _imp__CGFontCreateFontsWithPath(CFStringRef path);
CFMutableArrayRef CGCFArrayCreate(void);
CFMutableArrayRef _imp__CGCFArrayCreate(void);

CGContextRef CGBitmapContextCreate(void *data, size_t width, size_t height, size_t bitsPerComponent, size_t bytesPerRow, CGColorSpaceRef space, uint32_t bitmapInfo);
CGContextRef _imp__CGBitmapContextCreate(void *data, size_t width, size_t height, size_t bitsPerComponent, size_t bytesPerRow, CGColorSpaceRef space, uint32_t bitmapInfo);
CGContextRef CGContextRetain(CGContextRef c);
CGContextRef _imp__CGContextRetain(CGContextRef c);

CGColorRef CGColorRetain(CGColorRef color);
CGColorRef _imp__CGColorRetain(CGColorRef color);
CGColorRef CGColorGetConstantColor(CFStringRef colorName);
CGColorRef _imp__CGColorGetConstantColor(CFStringRef colorName);
CGColorRef CGColorCreate(CGColorSpaceRef space, const CGFloat* components);
CGColorRef _imp__CGColorCreate(CGColorSpaceRef space, const CGFloat* components);
CGColorRef CGColorCreateCopy(CGColorRef color);
CGColorRef _imp__CGColorCreateCopy(CGColorRef color);
CGColorRef CGColorCreateCopyWithAlpha(CGColorRef color, CGFloat alpha);
CGColorRef _imp__CGColorCreateCopyWithAlpha(CGColorRef color, CGFloat alpha);
CGColorRef CGColorCreateGenericGray(CGFloat gray, CGFloat alpha);
CGColorRef _imp__CGColorCreateGenericGray(CGFloat gray, CGFloat alpha);
CGColorRef CGColorCreateGenericRGB(CGFloat red, CGFloat green, CGFloat blue, CGFloat alpha);
CGColorRef _imp__CGColorCreateGenericRGB(CGFloat red, CGFloat green, CGFloat blue, CGFloat alpha);
CGColorRef CGColorCreateGenericCMYK(CGFloat cyan, CGFloat magenta, CGFloat yellow, CGFloat black, CGFloat alpha);
CGColorRef _imp__CGColorCreateGenericCMYK(CGFloat cyan, CGFloat magenta, CGFloat yellow, CGFloat black, CGFloat alpha);
CGColorRef CGColorCreateWithPattern(CGColorSpaceRef space, CGPatternRef pattern, const CGFloat* components);
CGColorRef _imp__CGColorCreateWithPattern(CGColorSpaceRef space, CGPatternRef pattern, const CGFloat* components);
CGColorRef CGColorCreateCopyByMatchingToColorSpace(CGColorSpaceRef, CGColorRenderingIntent intent, CGColorRef color, CFDictionaryRef options);
CGColorRef _imp__CGColorCreateCopyByMatchingToColorSpace(CGColorSpaceRef, CGColorRenderingIntent intent, CGColorRef color, CFDictionaryRef options);

CGColorSpaceRef CGImageGetColorSpace(CGImageRef image);
CGColorSpaceRef _imp__CGImageGetColorSpace(CGImageRef image);
CGColorSpaceRef CGColorGetColorSpace(CGColorRef color);
CGColorSpaceRef _imp__CGColorGetColorSpace(CGColorRef color);
CGColorSpaceRef CGColorSpaceCreateDeviceRGB(void);
CGColorSpaceRef _imp__CGColorSpaceCreateDeviceRGB(void);

CGColorRenderingIntent CGImageGetRenderingIntent(CGImageRef image);
CGColorRenderingIntent _imp__CGImageGetRenderingIntent(CGImageRef image);

CGPatternRef CGPatternRetain(CGPatternRef pattern);
CGPatternRef _imp__CGPatternRetain(CGPatternRef pattern);
CGPatternRef CGPatternCreate(void* info, CGRect bounds, CGAffineTransform matrix, CGFloat xStep, CGFloat yStep, CGPatternTiling tiling, bool isColored, const CGPatternCallbacks* callbacks);
CGPatternRef _imp__CGPatternCreate(void* info, CGRect bounds, CGAffineTransform matrix, CGFloat xStep, CGFloat yStep, CGPatternTiling tiling, bool isColored, const CGPatternCallbacks* callbacks);
CGPatternRef CGColorGetPattern(CGColorRef color);
CGPatternRef _imp__CGColorGetPattern(CGColorRef color);

CGGradientRef CGGradientCreateWithColors(CGColorSpaceRef space, CFArrayRef colors, const CGFloat* locations);
CGGradientRef _imp__CGGradientCreateWithColors(CGColorSpaceRef space, CFArrayRef colors, const CGFloat* locations);
CGGradientRef CGGradientCreateWithColorComponents(CGColorSpaceRef space, const CGFloat *components, const CGFloat *locations, size_t count);
CGGradientRef _imp__CGGradientCreateWithColorComponents(CGColorSpaceRef space, const CGFloat *components, const CGFloat *locations, size_t count);

CGImageAlphaInfo CGImageGetAlphaInfo(CGImageRef image);
CGImageAlphaInfo _imp__CGImageGetAlphaInfo(CGImageRef image);

CGBitmapInfo CGImageGetBitmapInfo(CGImageRef image);
CGBitmapInfo _imp__CGImageGetBitmapInfo(CGImageRef image);

CGDataProviderRef CGImageGetDataProvider(CGImageRef image);
CGDataProviderRef _imp__CGImageGetDataProvider(CGImageRef image);

const CGFloat* CGImageGetDecode(CGImageRef image);
const CGFloat* _imp__CGImageGetDecode(CGImageRef image);
const CGFloat* CGColorGetComponents(CGColorRef color);
const CGFloat* _imp__CGColorGetComponents(CGColorRef color);

size_t CGImageGetWidth(CGImageRef image);
size_t _imp__CGImageGetWidth(CGImageRef image);
size_t CGImageGetHeight(CGImageRef image);
size_t _imp__CGImageGetHeight(CGImageRef image);
size_t CGImageGetBitsPerComponent(CGImageRef image);
size_t _imp__CGImageGetBitsPerComponent(CGImageRef image);
size_t CGImageGetBitsPerPixel(CGImageRef image);
size_t _imp__CGImageGetBitsPerPixel(CGImageRef image);
size_t CGImageGetBytesPerRow(CGImageRef image);
size_t _imp__CGImageGetBytesPerRow(CGImageRef image);
size_t CGColorGetNumberOfComponents(CGColorRef color);
size_t _imp__CGColorGetNumberOfComponents(CGColorRef color);

bool CGRectEqualToRect(CGRect rect1, CGRect rect2);
bool _imp__CGRectEqualToRect(CGRect rect1, CGRect rect2);
bool CGRectIsNull(CGRect rect);
bool _imp__CGRectIsNull(CGRect rect);
bool CGRectIsEmpty(CGRect rect);
bool _imp__CGRectIsEmpty(CGRect rect);
bool CGRectIsInfinite(CGRect rect);
bool _imp__CGRectIsInfinite(CGRect rect);
bool CGRectContainsPoint(CGRect rect, CGPoint point);
bool _imp__CGRectContainsPoint(CGRect rect, CGPoint point);
bool CGRectContainsRect(CGRect rect1, CGRect rect2);
bool _imp__CGRectContainsRect(CGRect rect1, CGRect rect2);
bool CGRectIntersectsRect(CGRect rect1, CGRect rect2);
bool _imp__CGRectIntersectsRect(CGRect rect1, CGRect rect2);
bool CGAffineTransformIsIdentity(CGAffineTransform t);
bool _imp__CGAffineTransformIsIdentity(CGAffineTransform t);
bool CGAffineTransformEqualToTransform(CGAffineTransform t1, CGAffineTransform t2);
bool _imp__CGAffineTransformEqualToTransform(CGAffineTransform t1, CGAffineTransform t2);
bool CGContextIsPathEmpty(CGContextRef context);
bool _imp__CGContextIsPathEmpty(CGContextRef context);
bool CGImageGetShouldInterpolate(CGImageRef image);
bool _imp__CGImageGetShouldInterpolate(CGImageRef image);
bool CGImageIsMask(CGImageRef image);
bool _imp__CGImageIsMask(CGImageRef image);
bool CGPathEqualToPath(CGPathRef path1, CGPathRef path2);
bool _imp__CGPathEqualToPath(CGPathRef path1, CGPathRef path2);
bool CGPathIsEmpty(CGPathRef path);
bool _imp__CGPathIsEmpty(CGPathRef path);
bool CGPathIsRect(CGPathRef path, CGRect* rect);
bool _imp__CGPathIsRect(CGPathRef path, CGRect* rect);
bool CGPathContainsPoint(CGPathRef path, const CGAffineTransform* m, CGPoint point, bool eoFill);
bool _imp__CGPathContainsPoint(CGPathRef path, const CGAffineTransform* m, CGPoint point, bool eoFill);
bool CGRectMakeWithDictionaryRepresentation(CFDictionaryRef dict, CGRect* rect);
bool _imp__CGRectMakeWithDictionaryRepresentation(CFDictionaryRef dict, CGRect* rect);
bool CGSizeMakeWithDictionaryRepresentation(CFDictionaryRef dict, CGSize* size);
bool _imp__CGSizeMakeWithDictionaryRepresentation(CFDictionaryRef dict, CGSize* size);
bool CGPointMakeWithDictionaryRepresentation(CFDictionaryRef dict, CGPoint* point);
bool _imp__CGPointMakeWithDictionaryRepresentation(CFDictionaryRef dict, CGPoint* point);
bool CGColorEqualToColor(CGColorRef color1, CGColorRef color2);
bool _imp__CGColorEqualToColor(CGColorRef color1, CGColorRef color2);

bool CGFloatIsValid(CGFloat value);
bool _imp__CGFloatIsValid(CGFloat value);
bool CGCFDictionaryGetBoolean(CFDictionaryRef theDict, const void* key, bool* result);
bool _imp__CGCFDictionaryGetBoolean(CFDictionaryRef theDict, const void* key, bool* result);
bool CGCFDictionaryGetCFTypeRef(CFDictionaryRef theDict, const void* key, CFTypeID typeID, CFTypeRef* valuePtr);
bool _imp__CGCFDictionaryGetCFTypeRef(CFDictionaryRef theDict, const void* key, CFTypeID typeID, CFTypeRef* valuePtr);

CGAffineTransform CGAffineTransformMake(CGFloat a, CGFloat b, CGFloat c, CGFloat d, CGFloat tx, CGFloat ty);
CGAffineTransform _imp__CGAffineTransformMake(CGFloat a, CGFloat b, CGFloat c, CGFloat d, CGFloat tx, CGFloat ty);
CGAffineTransform CGAffineTransformMakeScale(CGFloat sx, CGFloat sy);
CGAffineTransform _imp__CGAffineTransformMakeScale(CGFloat sx, CGFloat sy);
CGAffineTransform CGAffineTransformMakeRotation(CGFloat angle);
CGAffineTransform _imp__CGAffineTransformMakeRotation(CGFloat angle);
CGAffineTransform CGAffineTransformMakeTranslation(CGFloat tx, CGFloat ty);
CGAffineTransform _imp__CGAffineTransformMakeTranslation(CGFloat tx, CGFloat ty);
CGAffineTransform CGAffineTransformTranslate(CGAffineTransform t, CGFloat tx, CGFloat ty);
CGAffineTransform _imp__CGAffineTransformTranslate(CGAffineTransform t, CGFloat tx, CGFloat ty);
CGAffineTransform CGAffineTransformScale(CGAffineTransform t, CGFloat sx, CGFloat sy);
CGAffineTransform _imp__CGAffineTransformScale(CGAffineTransform t, CGFloat sx, CGFloat sy);
CGAffineTransform CGAffineTransformRotate(CGAffineTransform t, CGFloat angle);
CGAffineTransform _imp__CGAffineTransformRotate(CGAffineTransform t, CGFloat angle);
CGAffineTransform CGAffineTransformTranslate(CGAffineTransform t, CGFloat tx, CGFloat ty);
CGAffineTransform _imp__CGAffineTransformTranslate(CGAffineTransform t, CGFloat tx, CGFloat ty);
CGAffineTransform CGAffineTransformInvert(CGAffineTransform t);
CGAffineTransform _imp__CGAffineTransformInvert(CGAffineTransform t);
CGAffineTransform CGAffineTransformConcat(CGAffineTransform t1, CGAffineTransform t2);
CGAffineTransform _imp__CGAffineTransformConcat(CGAffineTransform t1, CGAffineTransform t2);
CGAffineTransform CGContextGetCTM(CGContextRef c);
CGAffineTransform _imp__CGContextGetCTM(CGContextRef c);